### ISSUE TITLE
Incorrect values can be entered in the 'Deposit amount' field

### ISSUE THREAD

**Issue by jaminko** [jaminko/web.test#21]
1. Go to: https://localhost:5001/Calculator
2. Feel in 'Deposit amount' field with INVALID data (for example 100001) - according to requirements users can input up to 100,000 on deposit
3. Also @varajan should check regional settings for the 'Deposit amount' field because this field does not accept COMMAS with numeric expressions
![image](https://user-images.githubusercontent.com/96728802/199227708-90f2db5e-021b-4c55-908c-ca54567e93de.png)

**Comment by varajan** [comment]
3rd is a good point, but let's ignore it. It might be difficult to fix (for me)

**Comment by jaminko** [comment]
Fixed, works as expected

**Comment by jaminko** [comment]
@varajan 
After fix, 'Deposit amount' max value is 10 000 (instead 100 000)???
Can you have a look?

**Comment by jaminko** [comment]
Works as expected
