### ISSUE TITLE
Clear button works incorrect

### ISSUE THREAD

**Issue by jaminko** [jaminko/web.test#26]
1. Driver can't click on 'Clear' CTA button (check ClearButtonTest)
![image](https://user-images.githubusercontent.com/96728802/201198042-c8030cfb-e13a-4152-89ff-9cf61f611b21.png)

**Comment by varajan** [comment]
Wrong/incomplete bug description.

**Comment by jaminko** [comment]
Fixed (add WeitForReady method for History page)
