### ISSUE TITLE
Incorrect signatures for columns in the History table

### ISSUE THREAD

**Issue by jaminko** [jaminko/web.test#30]
1. Go to: https://localhost:5001/History
2. Check column signatures 
Expected: "Deposit amount", "Rate of interest", "Investment term", "Financial year", "Start date", "Income", "Intereset earned", "End date"
But was: "Amount", "%", "Term", "Year", "From", "To", "Interest", "Income"
![image](https://user-images.githubusercontent.com/96728802/201326307-9663821d-325a-401d-93e6-98991f935e4c.png)

**Comment by varajan** [comment]
Will not fix. With these titles the table looks ugly.
