### ISSUE TITLE
Incorrect values in the "Amount" and "%" columns in the History table

### ISSUE THREAD

**Issue by jaminko** [jaminko/web.test#31]
1. Go to: https://localhost:5001/History
2. Check the values in the "Amount" and "%" columns for any calculation (for example, the last one)
Expected: "177" for "Amount" column field and "64" for "%" column field
But was: "177.00" for "Amount" column field and "64%" for "%" column field
![image](https://user-images.githubusercontent.com/96728802/201327196-3e40c673-24eb-40c0-8860-f6467bdd2e9c.png)

**Comment by varajan** [comment]
Amount: it is expected behavior. Not fixing.
% - yep, maybe the `%` symbol should not be shown. Fixing.

**Comment by jaminko** [comment]
Fixed
