### ISSUE TITLE
Remind password button is not displayed

### ISSUE THREAD

**Issue by jaminko** [jaminko/web.test#4]
1. Go to: https://localhost:5001/
2. Check the 'Remind password' CTA button

Expected: On the page should be present 'Remind password' CTA button (according to requirements in README file)
But was: Remind password button is not displayed

![image](https://user-images.githubusercontent.com/96728802/198564721-5bd04fd6-a167-4ca9-95cf-573525c0e950.png)

**Comment by varajan** [comment]
The `Remind password` functionality will be implemented in future.
