### ISSUE TITLE
Incorrect signature for Deposit amount field

### ISSUE THREAD

**Issue by jaminko** [jaminko/web.test#6]
1. Go to: https://localhost:5001/Calculator
2. Check the signature for "Deposit Ammount" field
Expected: "Deposit amount." (according to requirements in README file)
But was: "Deposit Ammount:"
![image](https://user-images.githubusercontent.com/96728802/198832728-a06f6778-bb38-4533-8f10-24a492477873.png)

NOTE: I suggest making changes in the README file and replace 'Deposit amount.' with 'Deposit amount:'

**Comment by jaminko** [comment]
Hey @varajan,
In my opinion, you should make changes in the README file before next PR (replace 'Deposit amount.' with 'Deposit amount:')

**Comment by varajan** [comment]
The `readme` file is just a `email` from the customer. Let's keep it as is.

**Comment by jaminko** [comment]
Thanks for clarification
